### ISSUE TITLE
山水有相逢

### ISSUE THREAD

**Issue by orbli** [Trim21/gbf-teamraid-data#1]
Thanks for sharing the code, which gives me some ideas on improving my script.

Just out of curiosity, in my implementation I basically capture a traffic header and copy&paste it to my script. I have faced a problem those headers are expiring in about every hour. I see yours getting cookies directly from browser, does it mean you are also actively playing to keep the login instance active, so it uses cookies of your playing account to access? In other word, if you stop playing for an hour (or longer), will the script fail?

good luck 古戦場

**Comment by Trim21** [comment]
英文不太好 我就直接说中文了

我现在用的cookies是我上一次古战的时候开的小号 期间没有登录过 这几天才发现cookies仍然有效，就继续使用了

**Comment by orbli** [comment]
或許是接口請求的方法不同, 稍微再研究了一下, 似乎遊戲客戶端會在每次收到新接口response後用header裡面的"Set-Cookie"換成新的來保持登錄, 我保持更新Cookies後就好很多了

不過還是每一小時就會有一堆無效請求, 很麻煩 '_>`

**Comment by Trim21** [comment]
我是用了一个session来进行每次爬取的请求,接口的确也返回了`set-cookie`,但我从来没有把最后一次请求的cookies保存下来做为下次的初始cookies,一直用的是同一份初始cookies...

**Comment by Trim21** [comment]
你具体请求的是什么数据?

**Comment by orbli** [comment]
只有個人排名

**Comment by Trim21** [comment]
描述上好像是一样的啊...(

**Comment by orbli** [comment]
本來遊戲客戶端做請求時後面會另外有三個params, 看完你的寫法後我也乾脆就把他刪掉了, 或許也有關係

**Comment by Trim21** [comment]
对 那个params不但没有的时候也能请求成功,带上之后还有可能请求失败,什么用处都没有...
